name: 01 - Building Blocks
on: workflow_dispatch

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello world"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Success exit
        run: | 
          echo "I will do good"
          exit 0
      - name: Say goodbye
        run: echo "Goodbye!"
